[package]
name = "crosspoint-matrix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"

[[bin]]
name = "nets-to-chips"
required-features = ["std"]

[features]
default = []
std = []
